name: Generate Podcast Feeds
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v3
      - name: Run Feed Generator
        uses: shubham151/podcast-generator@main
      # - name: Setup Python
      #   uses: actions/setup-python@v4
      #   with: 
      #     python-version: '3.10'
      # - name: Install Dependencies
      #   run: |
      #     python -m pip install --upgrade pip
      #     pip install pyyaml
      # - name: Run Feed Generatior
      #   run: python feed.py
      # - name: push Repo
      #   run: | 
      #     git config user.name shubham151@actions
      #     git config user.email shubham151-actions@github.com
      #     git add .
      #     git commit -m "Modified Feed"
      #     git push
      
      
